---
- hosts : server
  become: true
  become_user: root
  become_method: sudo
  tasks :
    - name: Stop Blackbox Exporter
      command: systemctl stop blackbox_exporter
    - name: Disable Blackbox Exporter
      command: systemctl disable blackbox_exporter
    - name: Remove User Blackbox Exporter
      ansible.builtin.user:
        name: blackbox_exporter
        state: absent
        remove: yes
    - name: Remove blackbox_exporter
      file:
        path: /usr/local/bin/blackbox_exporter
        state: absent
    - name: Remove Directory for Blackbox
      file:
        path: /etc/blackbox_exporter
        state: absent
    - name: Remove Blackbox yml
      file:
        path: /etc/blackbox_exporter/blackbox_exporter.yml
        state: absent
    - name: Remove Blackbox Exporter Service File
      file:
        path: /etc/systemd/system/blackbox_exporter.service
        state: absent
    - name: Reload daemon
      command: systemctl daemon-reload
