---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Install Utilites
      yum:
        state: installed
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2

    - name: Install Docker Repository
      shell: yum-config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
      args:
        creates: /etc/yum.repos.d/docker-ce.repo

    - name: Install Kubernetes Repository
      shell: |
        cat <<EOF | sudo tee /etc/yum.repos.d/kubernetes.repo
        [kubernetes]
        name=Kubernetes
        baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
        enabled=1
        gpgcheck=1
        gpgkey=https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
        EOF
      args:
        creates: /etc/yum.repos.d/kubernetes.repo

    - name: Update YUM Repository
      command: /bin/yum clean all
      # args:
      #   warn: false

    - name: Install containerd packages
      yum:
        state: installed
        name: 
          - containerd.io

    - name: Enable kernel module containerd
      shell: |
          modprobe overlay
          modprobe br_netfilter
          cat <<EOF | sudo tee /etc/modules-load.d/containerd.conf
          overlay
          br_netfilter
          EOF
    
    - name: Configure sysctl networking containerd (1/2)
      shell: |
          cat <<EOF | sudo tee /etc/sysctl.d/99-kubernetes-cri.conf
          net.bridge.bridge-nf-call-iptables  = 1
          net.ipv4.ip_forward                 = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          EOF

    - name: Configure sysctl networking containerd (1/2)
      shell: |
          sysctl --system

    - name: Install k8s packages
      yum:
        state: installed
        name: 
          - kubelet
          - kubeadm
          - kubectl

    - name: Generate default config containerd
      shell: |
          containerd config default > /etc/containerd/config.toml

    - name: Update cgroup-driver containerd
      shell: |
          sed -i 's/SystemdCgroup\ \=\ false/SystemdCgroup\ \=\ true/g' /etc/containerd/config.toml

    - name: Start and enable docker
      shell: |
        systemctl enable containerd --now
    
    - name: Start and enable kubelet
      shell: |
        systemctl enable kubelet --now

