---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Install Utilites
      yum:
        state: installed
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2

    - name: Configure prerequisites (1/3)
      shell: |
          modprobe overlay
          modprobe br_netfilter
          cat <<EOF | sudo tee /etc/modules-load.d/containerd.conf
          overlay
          br_netfilter
          EOF

    - name: Configure prerequisites (2/3)
      shell: |
          cat <<EOF | sudo tee /etc/sysctl.d/99-kubernetes-cri.conf
          net.bridge.bridge-nf-call-iptables  = 1
          net.ipv4.ip_forward                 = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          EOF

    - name: Configure prerequisites (3/3)
      shell: |
          sysctl --system

    - name: Add Docker repository
      shell: yum-config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
      args:
        creates: /etc/yum.repos.d/docker-ce.repo

    - name: Update YUM Repository
      shell: /bin/yum clean all

    - name: Install containerd packages
      yum:
        state: installed
        name:
          - containerd.io

    - name: Create a configuration file for containerd and set it to default (1/2)
      shell: |
        mkdir -p /etc/containerd

    - name: Create a configuration file for containerd and set it to default (2/2)
      shell: |
        containerd config default | sudo tee /etc/containerd/config.toml

    - name: Update cgroup-driver containerd
      shell: |
          sed -i 's/SystemdCgroup\ \=\ false/SystemdCgroup\ \=\ true/g' /etc/containerd/config.toml

    - name: Restart containerd
      shell: |
          systemctl restart containerd

    - name: Enable containerd
      shell: |
        systemctl enable containerd

    - name: Add Kubernetes Repository
      shell: |
        cat <<EOF | sudo tee /etc/yum.repos.d/kubernetes.repo
        [kubernetes]
        name=Kubernetes
        baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
        enabled=1
        gpgcheck=1
        repo_gpgcheck=1
        gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
        EOF
      args:
        creates: /etc/yum.repos.d/kubernetes.repo

    - name: Install Kubernetes modules
      yum:
        state: installed
        name:
          - kubelet
          - kubeadm
          - kubectl

    - name: Turn off swap
      shell: |
          sed -i '/swap/d' /etc/fstab && swapoff -a

    - name: Enable kubelet
      shell: |
        systemctl enable kubelet
